<?php

/**
 * Yii app stub file. Autogenerated by yii2-stubs-generator (stubs console command).
 * Used for enhanced IDE code autocompletion.
 * Updated on 2016-08-28T00:50:08+0800
 */
class Yii extends \yii\BaseYii
{
    /**
     * @var BaseApplication|WebApplication|ConsoleApplication the application instance
     */
    public static $app;
}

/**
 * @property yii\redis\Connection $redis
 * @property yii\redis\Cache $cache
 * @property \common\components\JwtAuth $auth
 **/
abstract class BaseApplication extends yii\base\Application
{
}

/**
 **/
class WebApplication extends yii\web\Application
{
}

/**
 **/
class ConsoleApplication extends yii\console\Application
{

}